language: android

sudo: true

jdk:
  - oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - ABI=armeabi-v7a
    - EMU_FLAVOR=default # use google_apis flavor if no default flavor emulator
    # PATH order is incredibly important. e.g. the 'emulator' script exists in more than one place!
    - ANDROID_HOME=/usr/local/android-sdk
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
  matrix:
   - API=15 SKIP_COVERAGE=true
   - API=16 SKIP_COVERAGE=true AUDIO=-no-audio
   - API=17 SKIP_COVERAGE=true
   - API=18 SKIP_COVERAGE=true
   - API=19 SKIP_COVERAGE=true
   # API 20 doesn't have an emulator
   - API=21 SKIP_COVERAGE=true
   - API=22 SKIP_COVERAGE=true
   - API=23 SKIP_COVERAGE=true EMU_FLAVOR=google_apis
   # API 24 seems to be the most stable for coverage? do one run with it for Codacy.com
   - API=24 SKIP_COVERAGE=false
   - API=24 SKIP_COVERAGE=true
   - API=25 SKIP_COVERAGE=true EMU_FLAVOR=google_apis
   # API >= 26 don't have arm emulators, and Travis doesn't support x86

matrix:
  fast_finish: true # We can report success without waiting for these
  allow_failures:
    - env: API=15 SKIP_COVERAGE=true # sometimes emulator hangs, sometimes not - possibly fixable
    - env: API=23 SKIP_COVERAGE=true EMU_FLAVOR=google_apis # has permission errors
    - env: API=24 SKIP_COVERAGE=false # try coverage, but if it flakes, it isn't a fail
    - env: API=25 SKIP_COVERAGE=true EMU_FLAVOR=google_apis # has permission errors

android:
  components:
    # installing things this way vs 'sdkmanager' is deprecated, should move to sdkmanager over time
    - tools
    - platform-tools
    - tools              # a second time per Travis official docs, necessary for newest versions
    - build-tools-27.0.3 # Automated dependency from gradle - gradle will drive the changes
    - android-$API       # We need the API of the emulator we will run
    - android-26         # We need the API of the current build target
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

# Set up Code coverage tools
before_install:
  - if [[ ( "$SKIP_COVERAGE" == "false" ) ]]; then sudo apt-get install jq; fi
  - if [[ ( "$SKIP_COVERAGE" == "false" ) ]]; then wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url); fi

# Emulator Management: Create, Start and Wait
install:
  - echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid harmless sdkmanager warning
  - echo yes | sdkmanager tools # 'emulator' is deprecated, 'avdmanager' is current, this installs it
  - echo yes | sdkmanager "system-images;android-$API;$EMU_FLAVOR;$ABI" # install our emulator
  - echo no | avdmanager create avd --force -n test -k "system-images;android-$API;$EMU_FLAVOR;$ABI" -c 10M
  - emulator -avd test -engine classic -no-window $AUDIO -camera-back none -camera-front none -selinux permissive -qemu -m 2048 &

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - if [[ ( "$SKIP_COVERAGE" == "true" ) ]]; then ./gradlew test :AnkiDroid:connectedCheck; fi
  - if [[ ( "$SKIP_COVERAGE" == "false" ) ]]; then ./gradlew jacocoTestReport; fi

after_success:
  - if [[ ( "$SKIP_COVERAGE" == "false" ) ]]; then java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r AnkiDroid/build/reports/jacoco/report.xml; fi

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    - flerda+ankidroid-continuous@gmail.com
